// adflow-pro/adflow-pro/app/auth/register/page.tsx
'use client';
// app/auth/register/page.tsx
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { registerSchema, type RegisterInput } from '@/lib/validations/schemas';
import { createClient } from '@/lib/supabase/client';
import toast from 'react-hot-toast';
import { Zap, Eye, EyeOff, UserPlus } from 'lucide-react';

export default function RegisterPage() {
  const router = useRouter();
  const supabase = createClient();
  const [showPwd, setShowPwd] = useState(false);
  const [loading, setLoading] = useState(false);

  const { register, handleSubmit, formState: { errors } } = useForm<RegisterInput>({
    resolver: zodResolver(registerSchema),
  });

  async function onSubmit(data: RegisterInput) {
    setLoading(true);
    try {
      // Sign up with Supabase Auth
      const { data: authData, error } = await supabase.auth.signUp({
        email: data.email,
        password: data.password,
        options: {
          data: { full_name: data.full_name, role: 'client' },
        },
      });

      if (error) throw error;

      if (authData.user) {
        // Insert into public.users table
        await supabase.from('users').insert({
          id: authData.user.id,
          email: data.email,
          full_name: data.full_name,
          role: 'client',
        });

        toast.success('Account created! Welcome to AdFlow Pro.');
        router.push('/client');
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Registration failed';
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen mesh-bg flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, y: 30, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: 'spring', stiffness: 200, damping: 25 }}
        className="w-full max-w-md"
      >
        <Link href="/" className="flex items-center justify-center gap-2 mb-8">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center">
            <Zap size={18} className="text-white" />
          </div>
          <span className="font-display font-bold text-2xl text-white">AdFlow<span className="gradient-text">Pro</span></span>
        </Link>

        <div className="glass-strong rounded-2xl p-8 border border-white/10">
          <h1 className="font-display font-bold text-2xl text-white mb-1">Create an account</h1>
          <p className="text-white/40 text-sm mb-6">Start posting ads in minutes</p>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div>
              <label className="block text-xs text-white/50 mb-1.5">Full Name</label>
              <input {...register('full_name')} className="input-field" placeholder="Ahmed Ali" />
              {errors.full_name && <p className="text-red-400 text-xs mt-1">{errors.full_name.message}</p>}
            </div>

            <div>
              <label className="block text-xs text-white/50 mb-1.5">Email</label>
              <input type="email" {...register('email')} className="input-field" placeholder="you@example.com" />
              {errors.email && <p className="text-red-400 text-xs mt-1">{errors.email.message}</p>}
            </div>

            <div>
              <label className="block text-xs text-white/50 mb-1.5">Password</label>
              <div className="relative">
                <input
                  type={showPwd ? 'text' : 'password'}
                  {...register('password')}
                  className="input-field pr-10"
                  placeholder="Min. 6 characters"
                />
                <button type="button" onClick={() => setShowPwd(!showPwd)} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40">
                  {showPwd ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
              {errors.password && <p className="text-red-400 text-xs mt-1">{errors.password.message}</p>}
            </div>

            <div>
              <label className="block text-xs text-white/50 mb-1.5">Confirm Password</label>
              <input type="password" {...register('confirm_password')} className="input-field" placeholder="Repeat password" />
              {errors.confirm_password && <p className="text-red-400 text-xs mt-1">{errors.confirm_password.message}</p>}
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn-primary w-full flex items-center justify-center gap-2 py-3 mt-2 disabled:opacity-50"
            >
              <UserPlus size={16} />
              {loading ? 'Creating account...' : 'Create Account'}
            </button>
          </form>

          <p className="text-center text-sm text-white/40 mt-5">
            Already have an account?{' '}
            <Link href="/auth/login" className="text-violet-400 hover:text-violet-300">Sign in →</Link>
          </p>
          <p className="text-center text-xs text-white/25 mt-3">
            By registering you agree to our{' '}
            <Link href="/terms" className="text-white/40 hover:text-white/60">Terms of Service</Link>
          </p>
        </div>
      </motion.div>
    </div>
  );
}

// digital-committee-platform/src/app/auth/register/register.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../core/services/toast.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
<div class="min-h-screen flex items-center justify-center bg-surface-900 p-6"
  style="background: radial-gradient(ellipse at top, #1e1b4b 0%, #0f172a 60%)">

  <div class="auth-card animate-slide-up w-full max-w-lg">
    <!-- Header -->
    <div class="text-center mb-8">
      <div class="w-12 h-12 rounded-2xl bg-gradient-primary flex items-center justify-center mx-auto mb-4 shadow-glow">
        <span class="text-white font-bold text-xl">C</span>
      </div>
      <h2 class="text-2xl font-display font-bold text-white mb-1">Create your account</h2>
      <p class="text-slate-500 text-sm">Join thousands managing committees smarter</p>
    </div>

    <!-- Step indicator -->
    <div class="flex items-center gap-2 mb-8">
      @for (i of [1,2]; track i) {
        <div class="flex-1 h-1 rounded-full transition-all duration-300"
          [class]="step() >= i ? 'bg-gradient-primary' : 'bg-surface-700'"></div>
      }
    </div>

    <form (ngSubmit)="onSubmit()" #regForm="ngForm">
      <!-- Step 1 -->
      @if (step() === 1) {
        <div class="space-y-4 animate-slide-up">
          <div class="form-field">
            <label>Full Name</label>
            <input name="full_name" [(ngModel)]="data.full_name" required placeholder="Muhammad Zohaib" type="text">
          </div>
          <div class="form-field">
            <label>Email Address</label>
            <input name="email" [(ngModel)]="data.email" required type="email" placeholder="you@example.com">
          </div>
          <div class="form-field">
            <label>Phone Number</label>
            <input name="phone" [(ngModel)]="data.phone" type="tel" placeholder="+92 300 0000000">
          </div>
          <button type="button" (click)="nextStep()" class="btn-primary w-full justify-center py-3 mt-2">
            Continue →
          </button>
        </div>
      }

      <!-- Step 2 -->
      @if (step() === 2) {
        <div class="space-y-4 animate-slide-up">
          <div class="form-field">
            <label>Password</label>
            <input name="password" [(ngModel)]="data.password" required type="password"
              placeholder="Min. 8 characters" minlength="8">
          </div>
          <div class="form-field">
            <label>Confirm Password</label>
            <input name="confirm" [(ngModel)]="confirm" required type="password" placeholder="Repeat password">
            @if (confirm && confirm !== data.password) {
              <span class="error-msg">Passwords do not match</span>
            }
          </div>

          <label class="flex items-start gap-3 cursor-pointer mt-2">
            <input type="checkbox" name="terms" [(ngModel)]="terms" required
              class="mt-0.5 w-4 h-4 rounded accent-primary-500">
            <span class="text-xs text-slate-400 leading-relaxed">
              I agree to the <a href="#" class="text-primary-400">Terms of Service</a> and
              <a href="#" class="text-primary-400">Privacy Policy</a>
            </span>
          </label>

          @if (errorMsg()) {
            <div class="p-3 rounded-xl bg-danger-500/10 border border-danger-500/20 text-danger-400 text-sm">
              {{ errorMsg() }}
            </div>
          }

          <div class="flex gap-3">
            <button type="button" (click)="step.set(1)" class="btn-secondary flex-1 justify-center py-3">← Back</button>
            <button type="submit" class="btn-primary flex-1 justify-center py-3" [disabled]="loading()">
              @if (loading()) { <span class="spinner"></span> } @else { Create Account }
            </button>
          </div>
        </div>
      }
    </form>

    <p class="text-center text-sm text-slate-500 mt-6">
      Already have an account?
      <a routerLink="/auth/login" class="text-primary-400 hover:text-primary-300 font-medium ml-1">Sign in</a>
    </p>
  </div>
</div>
  `,
})
export class RegisterComponent {
  private auth  = inject(AuthService);
  private toast = inject(ToastService);
  private router = inject(Router);

  step     = signal(1);
  loading  = signal(false);
  errorMsg = signal('');
  confirm  = '';
  terms    = false;

  data = { full_name: '', email: '', phone: '', password: '' };

  nextStep() {
    if (!this.data.full_name || !this.data.email) {
      this.toast.warning('Missing fields', 'Please fill in all required fields.'); return;
    }
    this.step.set(2);
  }

  async onSubmit() {
    if (this.data.password !== this.confirm) { this.errorMsg.set('Passwords do not match.'); return; }
    if (!this.terms) { this.errorMsg.set('Please accept the Terms of Service.'); return; }
    this.loading.set(true); this.errorMsg.set('');
    try {
      await this.auth.register(this.data);
      this.toast.success('Account created!', 'Please check your email to verify your account.');
      this.router.navigate(['/auth/verify-email']);
    } catch (e: any) {
      this.errorMsg.set(e.message || 'Registration failed.');
    } finally {
      this.loading.set(false);
    }
  }
}
