// ElectionHub/election-system/src/pages/auth/Login.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { toast } from 'react-hot-toast';
import { Mail, Lock, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { data, error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });

      if (error) throw error;

      // Log audit
      if (data.user) {
        await supabase.from('audit_logs').insert({
          user_id: data.user.id,
          action: 'login',
          entity_type: 'auth',
        });
        
        // Fetch profile to redirect based on role
        const { data: profile } = await supabase
          .from('profiles')
          .select('role')
          .eq('id', data.user.id)
          .single();

        toast.success('Welcome back!');
        
        if (profile?.role === 'super_admin') navigate('/admin/dashboard');
        else if (profile?.role === 'election_creator') navigate('/creator/dashboard');
        else navigate('/voter/dashboard');
      }
    } catch (error) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-primaryBg px-4">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-md w-full glass-card p-8"
      >
        <div className="text-center mb-8">
          <Link to="/" className="text-2xl font-heading font-bold text-primaryGold mb-2 block">SecureVote<span className="text-textPrimary">Pro</span></Link>
          <h2 className="text-xl text-textSecondary">Sign in to your account</h2>
        </div>

        <form onSubmit={handleLogin} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-textSecondary mb-2">Email Address</label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Mail className="h-5 w-5 text-textMuted" />
              </div>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="input-field pl-10"
                placeholder="you@example.com"
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-textSecondary mb-2">Password</label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Lock className="h-5 w-5 text-textMuted" />
              </div>
              <input
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="input-field pl-10"
                placeholder="••••••••"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full btn-primary flex justify-center items-center"
          >
            {loading ? <Loader2 className="animate-spin h-5 w-5" /> : 'Sign In'}
          </button>
        </form>

        <p className="mt-6 text-center text-textSecondary text-sm">
          Don't have an account?{' '}
          <Link to="/signup" className="text-primaryGold hover:text-goldLight font-medium">
            Sign up
          </Link>
        </p>
      </motion.div>
    </div>
  );
}

// digital-committee-platform/src/app/auth/login/login.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../core/services/toast.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
<div class="min-h-screen flex bg-surface-900 overflow-hidden">

  <!-- Left Panel -->
  <div class="hidden lg:flex flex-col justify-between w-1/2 p-12 relative overflow-hidden"
    style="background: linear-gradient(135deg,#1e1b4b 0%,#0f172a 60%,#164e63 100%)">
    <div class="absolute inset-0 opacity-20"
      style="background-image: radial-gradient(circle at 30% 50%, #6366f1 0%, transparent 60%), radial-gradient(circle at 70% 80%, #06b6d4 0%, transparent 50%)"></div>
    <div class="relative z-10">
      <div class="flex items-center gap-3 mb-16">
        <div class="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center shadow-glow">
          <span class="text-white font-bold">C</span>
        </div>
        <span class="font-display font-bold text-white text-lg">CommitteePro</span>
      </div>
      <h1 class="text-4xl font-display font-bold text-white leading-tight mb-4">
        Manage Your Savings<br>
        <span class="gradient-text">Committees Smarter</span>
      </h1>
      <p class="text-slate-400 text-lg leading-relaxed">
        Track payments, manage members, and grow your trust reputation — all in one platform.
      </p>
    </div>
    <!-- Floating stats -->
    <div class="relative z-10 grid grid-cols-3 gap-4">
      @for (s of stats; track s.label) {
        <div class="glass-card p-4 text-center">
          <p class="text-2xl font-display font-bold gradient-text">{{ s.value }}</p>
          <p class="text-xs text-slate-500 mt-1">{{ s.label }}</p>
        </div>
      }
    </div>
  </div>

  <!-- Right Panel -->
  <div class="flex-1 flex items-center justify-center p-6">
    <div class="auth-card animate-slide-up">
      <div class="mb-8">
        <h2 class="text-2xl font-display font-bold text-white mb-1">Welcome back</h2>
        <p class="text-slate-500 text-sm">Sign in to your account to continue</p>
      </div>

      <form (ngSubmit)="onLogin()" #loginForm="ngForm" class="space-y-5">
        <div class="form-field">
          <label>Email address</label>
          <input type="email" name="email" [(ngModel)]="email" required placeholder="you@example.com"
            [class.error]="loginForm.submitted && !email">
        </div>

        <div class="form-field">
          <label>Password</label>
          <div class="relative">
            <input [type]="showPwd ? 'text' : 'password'" name="password" [(ngModel)]="password"
              required placeholder="••••••••" [class.error]="loginForm.submitted && !password">
            <button type="button" (click)="showPwd = !showPwd"
              class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-white text-sm">
              {{ showPwd ? '🙈' : '👁️' }}
            </button>
          </div>
        </div>

        <div class="flex items-center justify-between">
          <label class="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" name="remember" [(ngModel)]="remember"
              class="w-4 h-4 rounded accent-primary-500">
            <span class="text-xs text-slate-400">Remember me</span>
          </label>
          <a routerLink="/auth/forgot-password" class="text-xs text-primary-400 hover:text-primary-300 transition-colors">
            Forgot password?
          </a>
        </div>

        @if (errorMsg()) {
          <div class="p-3 rounded-xl bg-danger-500/10 border border-danger-500/20 text-danger-400 text-sm animate-fade-in">
            {{ errorMsg() }}
          </div>
        }

        <button type="submit" class="btn-primary w-full justify-center py-3" [disabled]="loading()">
          @if (loading()) { <span class="spinner"></span> } @else { Sign In }
        </button>
      </form>

      <div class="divider text-xs text-slate-600">or</div>

      <p class="text-center text-sm text-slate-500">
        Don't have an account?
        <a routerLink="/auth/register" class="text-primary-400 hover:text-primary-300 font-medium ml-1">Sign up free</a>
      </p>
    </div>
  </div>
</div>
  `,
})
export class LoginComponent {
  private auth  = inject(AuthService);
  private toast = inject(ToastService);
  private router= inject(Router);

  email    = '';  password = '';
  remember = false; showPwd = false;
  loading  = signal(false);
  errorMsg = signal('');

  stats = [
    { value: '10K+', label: 'Active Users' },
    { value: '₨2B+', label: 'Total Managed' },
    { value: '99.9%', label: 'Uptime' },
  ];

  async onLogin() {
    if (!this.email || !this.password) return;
    this.loading.set(true); this.errorMsg.set('');
    try {
      await this.auth.login({ email: this.email, password: this.password });
      this.toast.success('Welcome back!', 'Logged in successfully.');
      this.router.navigate(['/dashboard']);
    } catch (e: any) {
      this.errorMsg.set(e.message || 'Login failed. Please try again.');
    } finally {
      this.loading.set(false);
    }
  }
}
