// adflow-pro/adflow-pro/app/auth/login/page.tsx
'use client';
// app/auth/login/page.tsx
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { loginSchema, type LoginInput } from '@/lib/validations/schemas';
import { createClient } from '@/lib/supabase/client';
import toast from 'react-hot-toast';
import { Zap, Eye, EyeOff, LogIn } from 'lucide-react';

export default function LoginPage() {
  const router = useRouter();
  const supabase = createClient();
  const [showPwd, setShowPwd] = useState(false);
  const [loading, setLoading] = useState(false);

  const { register, handleSubmit, formState: { errors } } = useForm<LoginInput>({
    resolver: zodResolver(loginSchema),
  });

  async function onSubmit(data: LoginInput) {
    setLoading(true);
    const { error } = await supabase.auth.signInWithPassword({
      email: data.email,
      password: data.password,
    });
    if (error) {
      toast.error(error.message);
      setLoading(false);
      return;
    }

    // Fetch role to redirect properly
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      const { data: profile } = await supabase.from('users').select('role').eq('id', user.id).single();
      const role = profile?.role ?? 'client';
      const dest = role === 'super_admin' ? '/superadmin' : role === 'admin' ? '/admin' : role === 'moderator' ? '/moderator' : '/client';
      toast.success('Welcome back!');
      router.push(dest);
    }
  }

  return (
    <div className="min-h-screen mesh-bg flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, y: 30, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: 'spring', stiffness: 200, damping: 25 }}
        className="w-full max-w-md"
      >
        {/* Logo */}
        <Link href="/" className="flex items-center justify-center gap-2 mb-8">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center">
            <Zap size={18} className="text-white" />
          </div>
          <span className="font-display font-bold text-2xl text-white">AdFlow<span className="gradient-text">Pro</span></span>
        </Link>

        <div className="glass-strong rounded-2xl p-8 border border-white/10">
          <h1 className="font-display font-bold text-2xl text-white mb-1">Welcome back</h1>
          <p className="text-white/40 text-sm mb-6">Sign in to your account</p>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div>
              <label className="block text-xs text-white/50 mb-1.5">Email</label>
              <input
                type="email"
                {...register('email')}
                className="input-field"
                placeholder="you@example.com"
              />
              {errors.email && <p className="text-red-400 text-xs mt-1">{errors.email.message}</p>}
            </div>

            <div>
              <label className="block text-xs text-white/50 mb-1.5">Password</label>
              <div className="relative">
                <input
                  type={showPwd ? 'text' : 'password'}
                  {...register('password')}
                  className="input-field pr-10"
                  placeholder="••••••••"
                />
                <button
                  type="button"
                  onClick={() => setShowPwd(!showPwd)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40 hover:text-white"
                >
                  {showPwd ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
              {errors.password && <p className="text-red-400 text-xs mt-1">{errors.password.message}</p>}
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn-primary w-full flex items-center justify-center gap-2 py-3 mt-2 disabled:opacity-50"
            >
              <LogIn size={16} />
              {loading ? 'Signing in...' : 'Sign In'}
            </button>
          </form>

          <p className="text-center text-sm text-white/40 mt-5">
            Don't have an account?{' '}
            <Link href="/auth/register" className="text-violet-400 hover:text-violet-300">
              Create one →
            </Link>
          </p>
        </div>
      </motion.div>
    </div>
  );
}

// digital-committee-platform/src/app/auth/login/login.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../core/services/toast.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
<div class="min-h-screen flex bg-surface-900 overflow-hidden">

  <!-- Left Panel -->
  <div class="hidden lg:flex flex-col justify-between w-1/2 p-12 relative overflow-hidden"
    style="background: linear-gradient(135deg,#1e1b4b 0%,#0f172a 60%,#164e63 100%)">
    <div class="absolute inset-0 opacity-20"
      style="background-image: radial-gradient(circle at 30% 50%, #6366f1 0%, transparent 60%), radial-gradient(circle at 70% 80%, #06b6d4 0%, transparent 50%)"></div>
    <div class="relative z-10">
      <div class="flex items-center gap-3 mb-16">
        <div class="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center shadow-glow">
          <span class="text-white font-bold">C</span>
        </div>
        <span class="font-display font-bold text-white text-lg">CommitteePro</span>
      </div>
      <h1 class="text-4xl font-display font-bold text-white leading-tight mb-4">
        Manage Your Savings<br>
        <span class="gradient-text">Committees Smarter</span>
      </h1>
      <p class="text-slate-400 text-lg leading-relaxed">
        Track payments, manage members, and grow your trust reputation — all in one platform.
      </p>
    </div>
    <!-- Floating stats -->
    <div class="relative z-10 grid grid-cols-3 gap-4">
      @for (s of stats; track s.label) {
        <div class="glass-card p-4 text-center">
          <p class="text-2xl font-display font-bold gradient-text">{{ s.value }}</p>
          <p class="text-xs text-slate-500 mt-1">{{ s.label }}</p>
        </div>
      }
    </div>
  </div>

  <!-- Right Panel -->
  <div class="flex-1 flex items-center justify-center p-6">
    <div class="auth-card animate-slide-up">
      <div class="mb-8">
        <h2 class="text-2xl font-display font-bold text-white mb-1">Welcome back</h2>
        <p class="text-slate-500 text-sm">Sign in to your account to continue</p>
      </div>

      <form (ngSubmit)="onLogin()" #loginForm="ngForm" class="space-y-5">
        <div class="form-field">
          <label>Email address</label>
          <input type="email" name="email" [(ngModel)]="email" required placeholder="you@example.com"
            [class.error]="loginForm.submitted && !email">
        </div>

        <div class="form-field">
          <label>Password</label>
          <div class="relative">
            <input [type]="showPwd ? 'text' : 'password'" name="password" [(ngModel)]="password"
              required placeholder="••••••••" [class.error]="loginForm.submitted && !password">
            <button type="button" (click)="showPwd = !showPwd"
              class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-white text-sm">
              {{ showPwd ? '🙈' : '👁️' }}
            </button>
          </div>
        </div>

        <div class="flex items-center justify-between">
          <label class="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" name="remember" [(ngModel)]="remember"
              class="w-4 h-4 rounded accent-primary-500">
            <span class="text-xs text-slate-400">Remember me</span>
          </label>
          <a routerLink="/auth/forgot-password" class="text-xs text-primary-400 hover:text-primary-300 transition-colors">
            Forgot password?
          </a>
        </div>

        @if (errorMsg()) {
          <div class="p-3 rounded-xl bg-danger-500/10 border border-danger-500/20 text-danger-400 text-sm animate-fade-in">
            {{ errorMsg() }}
          </div>
        }

        <button type="submit" class="btn-primary w-full justify-center py-3" [disabled]="loading()">
          @if (loading()) { <span class="spinner"></span> } @else { Sign In }
        </button>
      </form>

      <div class="divider text-xs text-slate-600">or</div>

      <p class="text-center text-sm text-slate-500">
        Don't have an account?
        <a routerLink="/auth/register" class="text-primary-400 hover:text-primary-300 font-medium ml-1">Sign up free</a>
      </p>
    </div>
  </div>
</div>
  `,
})
export class LoginComponent {
  private auth  = inject(AuthService);
  private toast = inject(ToastService);
  private router= inject(Router);

  email    = '';  password = '';
  remember = false; showPwd = false;
  loading  = signal(false);
  errorMsg = signal('');

  stats = [
    { value: '10K+', label: 'Active Users' },
    { value: '₨2B+', label: 'Total Managed' },
    { value: '99.9%', label: 'Uptime' },
  ];

  async onLogin() {
    if (!this.email || !this.password) return;
    this.loading.set(true); this.errorMsg.set('');
    try {
      await this.auth.login({ email: this.email, password: this.password });
      this.toast.success('Welcome back!', 'Logged in successfully.');
      this.router.navigate(['/dashboard']);
    } catch (e: any) {
      this.errorMsg.set(e.message || 'Login failed. Please try again.');
    } finally {
      this.loading.set(false);
    }
  }
}
