// digital-committee-platform/src/app/auth/register/register.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../core/services/toast.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
<div class="min-h-screen flex items-center justify-center bg-surface-900 p-6"
  style="background: radial-gradient(ellipse at top, #1e1b4b 0%, #0f172a 60%)">

  <div class="auth-card animate-slide-up w-full max-w-lg">
    <!-- Header -->
    <div class="text-center mb-8">
      <div class="w-12 h-12 rounded-2xl bg-gradient-primary flex items-center justify-center mx-auto mb-4 shadow-glow">
        <span class="text-white font-bold text-xl">C</span>
      </div>
      <h2 class="text-2xl font-display font-bold text-white mb-1">Create your account</h2>
      <p class="text-slate-500 text-sm">Join thousands managing committees smarter</p>
    </div>

    <!-- Step indicator -->
    <div class="flex items-center gap-2 mb-8">
      @for (i of [1,2]; track i) {
        <div class="flex-1 h-1 rounded-full transition-all duration-300"
          [class]="step() >= i ? 'bg-gradient-primary' : 'bg-surface-700'"></div>
      }
    </div>

    <form (ngSubmit)="onSubmit()" #regForm="ngForm">
      <!-- Step 1 -->
      @if (step() === 1) {
        <div class="space-y-4 animate-slide-up">
          <div class="form-field">
            <label>Full Name</label>
            <input name="full_name" [(ngModel)]="data.full_name" required placeholder="Muhammad Zohaib" type="text">
          </div>
          <div class="form-field">
            <label>Email Address</label>
            <input name="email" [(ngModel)]="data.email" required type="email" placeholder="you@example.com">
          </div>
          <div class="form-field">
            <label>Phone Number</label>
            <input name="phone" [(ngModel)]="data.phone" type="tel" placeholder="+92 300 0000000">
          </div>
          <button type="button" (click)="nextStep()" class="btn-primary w-full justify-center py-3 mt-2">
            Continue →
          </button>
        </div>
      }

      <!-- Step 2 -->
      @if (step() === 2) {
        <div class="space-y-4 animate-slide-up">
          <div class="form-field">
            <label>Password</label>
            <input name="password" [(ngModel)]="data.password" required type="password"
              placeholder="Min. 8 characters" minlength="8">
          </div>
          <div class="form-field">
            <label>Confirm Password</label>
            <input name="confirm" [(ngModel)]="confirm" required type="password" placeholder="Repeat password">
            @if (confirm && confirm !== data.password) {
              <span class="error-msg">Passwords do not match</span>
            }
          </div>

          <label class="flex items-start gap-3 cursor-pointer mt-2">
            <input type="checkbox" name="terms" [(ngModel)]="terms" required
              class="mt-0.5 w-4 h-4 rounded accent-primary-500">
            <span class="text-xs text-slate-400 leading-relaxed">
              I agree to the <a href="#" class="text-primary-400">Terms of Service</a> and
              <a href="#" class="text-primary-400">Privacy Policy</a>
            </span>
          </label>

          @if (errorMsg()) {
            <div class="p-3 rounded-xl bg-danger-500/10 border border-danger-500/20 text-danger-400 text-sm">
              {{ errorMsg() }}
            </div>
          }

          <div class="flex gap-3">
            <button type="button" (click)="step.set(1)" class="btn-secondary flex-1 justify-center py-3">← Back</button>
            <button type="submit" class="btn-primary flex-1 justify-center py-3" [disabled]="loading()">
              @if (loading()) { <span class="spinner"></span> } @else { Create Account }
            </button>
          </div>
        </div>
      }
    </form>

    <p class="text-center text-sm text-slate-500 mt-6">
      Already have an account?
      <a routerLink="/auth/login" class="text-primary-400 hover:text-primary-300 font-medium ml-1">Sign in</a>
    </p>
  </div>
</div>
  `,
})
export class RegisterComponent {
  private auth  = inject(AuthService);
  private toast = inject(ToastService);
  private router = inject(Router);

  step     = signal(1);
  loading  = signal(false);
  errorMsg = signal('');
  confirm  = '';
  terms    = false;

  data = { full_name: '', email: '', phone: '', password: '' };

  nextStep() {
    if (!this.data.full_name || !this.data.email) {
      this.toast.warning('Missing fields', 'Please fill in all required fields.'); return;
    }
    this.step.set(2);
  }

  async onSubmit() {
    if (this.data.password !== this.confirm) { this.errorMsg.set('Passwords do not match.'); return; }
    if (!this.terms) { this.errorMsg.set('Please accept the Terms of Service.'); return; }
    this.loading.set(true); this.errorMsg.set('');
    try {
      await this.auth.register(this.data);
      this.toast.success('Account created!', 'Please check your email to verify your account.');
      this.router.navigate(['/auth/verify-email']);
    } catch (e: any) {
      this.errorMsg.set(e.message || 'Registration failed.');
    } finally {
      this.loading.set(false);
    }
  }
}

// Adflow-Pro/app/auth/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { createClient } from '@/lib/supabase/client';
import toast from 'react-hot-toast';

export default function RegisterPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    full_name: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const supabase = createClient();
      const { error } = await supabase.auth.signUp({
        email: formData.email,
        password: formData.password,
        options: {
          data: {
            full_name: formData.full_name,
            role: 'client',
          },
        },
      });

      if (error) throw error;

      toast.success('Account created. Check your inbox for verification.');
      router.push('/auth/login');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to register');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(14,165,233,0.18),_transparent_28%),linear-gradient(180deg,_#fffdf8_0%,_#ffffff_50%,_#f8fafc_100%)] px-4 py-10">
      <div className="mx-auto grid min-h-[calc(100vh-5rem)] max-w-6xl items-center gap-8 lg:grid-cols-[0.95fr_1.05fr]">
        <Card className="order-2 rounded-[2rem] border-slate-200 bg-white/85 shadow-[0_20px_60px_rgba(15,23,42,0.08)] lg:order-1">
          <CardContent className="p-8">
            <div className="mb-6">
              <Link href="/" className="text-lg font-semibold text-slate-950">AdFlow Pro</Link>
              <h2 className="mt-3 text-3xl font-semibold tracking-tight">Create your client account</h2>
              <p className="mt-2 text-sm text-slate-600">Start submitting campaigns into the workflow engine.</p>
            </div>
            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="space-y-2">
                <Label htmlFor="full_name">Full name</Label>
                <Input id="full_name" value={formData.full_name} onChange={(e) => setFormData({ ...formData, full_name: e.target.value })} required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" type="password" minLength={8} value={formData.password} onChange={(e) => setFormData({ ...formData, password: e.target.value })} required />
                <p className="text-xs text-slate-500">At least 8 characters</p>
              </div>
              <Button type="submit" disabled={loading} className="w-full rounded-full bg-slate-950 py-6 text-base hover:bg-slate-800">
                {loading ? 'Creating account...' : 'Create account'}
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </form>
            <p className="mt-5 text-sm text-slate-600">
              Already registered?{' '}
              <Link href="/auth/login" className="font-medium text-orange-600 hover:text-orange-500">
                Sign in
              </Link>
            </p>
          </CardContent>
        </Card>

        <div className="order-1 rounded-[2rem] bg-slate-950 p-8 text-white shadow-[0_40px_120px_rgba(15,23,42,0.24)] lg:order-2">
          <p className="text-xs uppercase tracking-[0.35em] text-orange-300">Workflow Marketplace</p>
          <h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">
            Publish only when content, payment, and timing all line up.
          </h1>
          <div className="mt-6 space-y-4 text-sm leading-7 text-slate-300">
            <p>Clients submit ads and payment proofs.</p>
            <p>Moderators approve content quality and compliance.</p>
            <p>Admins verify revenue events and schedule launch windows.</p>
            <p>Only approved, non-expired campaigns reach the public marketplace.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
